#!/usr/bin/env bash

#
# Title: Search Inside Files
# Description: Search patterns inside files.
# Tags: Grep, Find, Search, Files
#

pattern="$1"
extension="*$2"

find . -name "$extension" -exec grep -EHni "$pattern" {} \;
