#!/usr/bin/env bash

#
# Title: Loop
# Description: Loop in a command time to time
# Tags: Loop, command, time
#

loop=${@:1}
interval=${@:2}
command=${@:3}
args=${@:4:}

for i in 1:$loop; then
    $command $args
    sleep $interval
endfor
