#!/usr/bin/env bash

#
# Title: Timeit
# Description: Calculate the average time of program execution.
# Tags: Performance, timeit
#
# Parameters
# ----------
# - num_repeat: Repeat number to make the average. Min > 1
# - exec_command: Command to execute
#
# Usage example
# -------------
# Command: timeit 10 wc -l result.log | tr '\n' ' '
# Result: Avg. Time [10 runs]: 0.0012s
#

num_repeat="$1"
exec_command="${@:2}"

if [ $num_repeat -lt 2 ]; then
    num_repeat=2
fi

id=$RANDOM$RANDOM$RANDOM$RANDOM
log_file="/tmp/${id}.log"

parallel --linebuffer -j0 -P0 -n0 -q time $exec_command 2> "$log_file" 1> /dev/null ::: $( seq $num_repeat )
(echo -e "type\ttime"; grep -E "real\s*?(.*?)s$" "$log_file") \
    | in2csv -f csv \
    | csvcut -c2 \
    | tail -n+2 \
    | xargs -n1 python -c "import sys; hr, min, sec = [float(x) for x in sys.argv[1].split(':')]; print hr*3600 + min*60 + sec" \
    | csvstat --mean \
    | xargs printf "Avg. Time [%s runs]: %ss" $num_repeat 
rm "$log_file"
