#!/usr/bin/env bash

#
# Single thread python server for files.
#

# Set Port
port=$1
if [ -z $port ]; then
    port=8888
fi

#
# Set IP
#
ip=$2
if [ -z $ip ]; then
    ip="0.0.0.0"
fi

sudo python -m SimpleHTTPServer $port $ip
